name: Print pull request context
on:
    workflow_dispatch:
    pull_request:
        types: [opened, reopened]
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - name: print PR context
              # Через объект github можно получить доступ к переменным конекста.
              run: echo "${{ toJSON(github.event) }}"
