name: Demo Workflow
on:
    push:
        branches:
            - "master"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get source code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Test application
              run: npm run test

            - name: Lint application
              run: npm run lint

            - name: Build application
              run: npm run build
# ПО дефолту джобы работают параллельно
# Но можно выстроить зависимости, чтобы если тесты упали, не пошёл билд.
# Поле needs.
# Такие процессы, как тест, линтинг и билд, можно не разьиавать на джобы, а разбить на степы внутри одной джобы
